name: Deploy Infrastructure & Function

on:
  workflow_dispatch:

permissions:
  id-token: write   
  contents: read   

env:
  # ARM_* for Terraform AzureRM provider
  ARM_CLIENT_ID:     ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID:     ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Export TF_VARs from GitHub Secrets
      run: |
        echo "TF_VAR_apikey=${{ secrets.APIKEY }}" >> $GITHUB_ENV
        echo "TF_VAR_sql_admin_password=${{ secrets.SQL_ADMIN_PASSWORD }}" >> $GITHUB_ENV
        echo "TF_VAR_sp_object_id=${{ secrets.SP_OBJECT_ID }}"             >> $GITHUB_ENV
        echo "TF_VAR_nba_endpoint=${{ secrets.NBA_ENDPOINT }}"            >> $GITHUB_ENV
        echo "TF_VAR_subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}"        >> $GITHUB_ENV
        
    - name: List directory contents
      run: ls -la nba_refresh

    - name: Terraform Init
      run: terraform -chdir=Terraform init
      
    - name: Terraform Import Existing RG
      # Try to import the RG; if it’s already in state this will fail,
      # so we “|| true” to avoid the job stopping on that error.
      run: |
        terraform -chdir=Terraform import azurerm_resource_group.rg \
          "/subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/AzureDatalake-RG" || true
    - name: Terraform Import Key Vault Access Policy
    - run: |
        terraform -chdir=Terraform import \
          azurerm_key_vault_access_policy.terraform_sp \
          "/subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/AzureDatalake-RG/providers/Microsoft.KeyVault/vaults/mydatalakekeyvault673/objectId/${{ secrets.SP_OBJECT_ID }}" || true

    - name: Terraform Validate
      run: terraform -chdir=Terraform validate

    - name: Terraform Plan
      run: terraform -chdir=Terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform -chdir=Terraform apply -auto-approve

    - name: Set up Python for Function deployment
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Deploy Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: datafunctionapp673
        package: 'nba_refresh'

